-- Baseline schema (matches the JPA entities before analysis provenance was added).
-- Existing databases created by Hibernate ddl-auto are baselined at version 1 and skip this script.

create table reviews (
    id                  bigint generated by default as identity primary key,
    guest_name          varchar(100)  not null,
    review_text         varchar(4000) not null,
    rating              integer,
    analysis_status     varchar(20),
    analysis_error      varchar(1000),
    analysis_updated_at timestamp(6) with time zone,
    submitted_at        timestamp(6) with time zone not null,
    updated_at          timestamp(6) with time zone not null,
    constraint ck_reviews_rating check (rating between 1 and 5),
    constraint ck_reviews_analysis_status check (analysis_status in ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'))
);

create index idx_reviews_submitted_at on reviews (submitted_at);
create index idx_reviews_analysis_status on reviews (analysis_status);

create table review_analyses (
    id               bigint generated by default as identity primary key,
    review_id        bigint        not null,
    sentiment        varchar(20)   not null,
    sentiment_score  integer       not null,
    main_topic       varchar(40)   not null,
    manager_response varchar(4000) not null,
    created_at       timestamp(6) with time zone not null,
    updated_at       timestamp(6) with time zone not null,
    constraint uk_review_analyses_review unique (review_id),
    constraint fk_review_analyses_review foreign key (review_id) references reviews (id),
    constraint ck_review_analyses_score check (sentiment_score between 0 and 100),
    constraint ck_review_analyses_sentiment check (sentiment in ('POSITIVE', 'NEUTRAL', 'NEGATIVE')),
    constraint ck_review_analyses_main_topic check (main_topic in ('CLEANLINESS', 'STAFF', 'ACCESSIBILITY', 'FOOD',
        'LOCATION', 'AMENITIES', 'VALUE', 'COMFORT', 'CHECK_IN', 'CHECK_OUT', 'NOISE', 'SAFETY', 'OTHER'))
);

create index idx_review_analyses_sentiment on review_analyses (sentiment);
create index idx_review_analyses_main_topic on review_analyses (main_topic);

create table review_topics (
    review_analysis_id bigint      not null,
    topic              varchar(40) not null,
    primary key (review_analysis_id, topic),
    constraint fk_review_topics_analysis foreign key (review_analysis_id) references review_analyses (id),
    constraint ck_review_topics_topic check (topic in ('CLEANLINESS', 'STAFF', 'ACCESSIBILITY', 'FOOD',
        'LOCATION', 'AMENITIES', 'VALUE', 'COMFORT', 'CHECK_IN', 'CHECK_OUT', 'NOISE', 'SAFETY', 'OTHER'))
);

create table hotel_policy_documents (
    id             bigint generated by default as identity primary key,
    title          varchar(200)  not null,
    category       varchar(80)   not null,
    content        varchar(8000) not null,
    source         varchar(200),
    effective_date date,
    active         boolean       not null,
    created_at     timestamp(6) with time zone not null,
    updated_at     timestamp(6) with time zone not null
);

create index idx_policy_category on hotel_policy_documents (category);
create index idx_policy_active on hotel_policy_documents (active);

create table hotel_policy_tags (
    policy_id bigint      not null,
    tag       varchar(60) not null,
    primary key (policy_id, tag),
    constraint fk_hotel_policy_tags_policy foreign key (policy_id) references hotel_policy_documents (id)
);
