-- Application users with BCrypt password hashes and a single role.

create table app_users (
    id            bigint generated by default as identity primary key,
    username      varchar(100) not null,
    password_hash varchar(100) not null,
    role          varchar(20)  not null,
    enabled       boolean      not null,
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    constraint uk_app_users_username unique (username),
    constraint ck_app_users_role check (role in ('ADMIN', 'MANAGER', 'VIEWER'))
);
