-- Manager reply workflow: every change is a new revision; the latest one is the current reply.

create table review_reply_revisions (
    id         bigint generated by default as identity primary key,
    review_id  bigint        not null,
    status     varchar(20)   not null,
    text       varchar(4000) not null,
    author     varchar(100)  not null,
    created_at timestamp(6) with time zone not null,
    constraint fk_reply_revisions_review foreign key (review_id) references reviews (id),
    constraint ck_reply_revisions_status check (status in ('DRAFT', 'EDITED', 'APPROVED', 'SENT'))
);

create index idx_reply_revisions_review on review_reply_revisions (review_id, id);
